services:
  app-vendedores:
    build: .
    container_name: app-vendedores
    ports:
      - "9002:8000"
    environment:
      - SHEETS_URL=https://script.google.com/macros/s/AKfycby9cTlYMta4df8jM0QktvLQRZDDn2bOD7RyoumxZyaGb9qCVXMQ0rHMqNUDQ75paropbA/exec
      - SYNC_INTERVAL=300
    volumes:
      - ./data:/data
    restart: unless-stopped
